package com.ldb.truck.Model.Login.VicicleFooter;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class VicicleFooter {
    private String key_id;
    private String f_BRANCH;
    private String f_YEAR  ;
    private String F_CAR_TYPE;
    private String f_DATEEXPRIED;
    private String f_CARD_NO ;
    private String f_LEKKUNZEE  ;
    private String f_PAO   ;
    private String f_KORKC ;
    private String f_TOLOCKTU;
    private String f_SO    ;
    private String f_PABUD ;
    private String f_FAIKHANG;
    private String f_FAITHAIY;
    private String f_BGTHOM;
    private String f_GALATY_NO  ;
    private String f_GALATY_DEP ;
    private String l_TRIES_1;
    private String l_TRIES_2;
    private String l_TRIES_3;
    private String l_TRIES_4;
    private String l_TRIES_5;
    private String l_TRIES_6;
    private String l_TRIES_7;
    private String l_TRIES_8;
    private String l_TRIES_DATE_1;
    private String l_TRIES_DATE_2;
    private String l_TRIES_DATE_3;
    private String l_TRIES_DATE_4;
    private String l_TRIES_DATE_5;
    private String l_TRIES_DATE_6;
    private String l_TRIES_DATE_7;
    private String l_TRIES_DATE_8;
    private String l_TRIES_KM_1  ;
    private String l_TRIES_KM_2  ;
    private String l_TRIES_KM_3  ;
    private String l_TRIES_KM_4  ;
    private String l_TRIES_KM_5  ;
    private String l_TRIES_KM_6  ;
    private String l_TRIES_KM_7  ;
    private String l_TRIES_KM_8  ;
    private String r_TRIES_1;
    private String r_TRIES_2;
    private String r_TRIES_3;
    private String r_TRIES_4;
    private String r_TRIES_5;
    private String r_TRIES_6;
    private String r_TRIES_7;
    private String r_TRIES_8;
    private String r_TRIES_DATE_1;
    private String r_TRIES_DATE_2;
    private String r_TRIES_DATE_3;
    private String r_TRIES_DATE_4;
    private String r_TRIES_DATE_5;
    private String r_TRIES_DATE_6;
    private String r_TRIES_DATE_7;
    private String r_TRIES_DATE_8;
    private String r_TRIES_KM_1  ;
    private String r_TRIES_KM_2  ;
    private String r_TRIES_KM_3  ;
    private String r_TRIES_KM_4  ;
    private String r_TRIES_KM_5  ;
    private String r_TRIES_KM_6  ;
    private String r_TRIES_KM_7  ;
    private String r_TRIES_KM_8  ;
    private String f_STATUS;
    private String hIS_DATE;
    private String his_REASON;
    private String f_KM1;
    private String f_KM2;
    private String f_KM3;
    private String f_KM4;
    private String f_KM5;
    private String f_KM6;
    private String f_KM7;
    private String f_KM8;
    private String f_KM9;
    private String f_KM10;
    private String f_KM11;
    private String f_KM12;
    private String f_KM13;
    private String f_KM14;
    private String f_KM15;
    private String f_KM16;
    private String f_KM_LL1;
    private String f_KM_LL2;
    private String f_KM_LL3;
    private String f_KM_LL4;
    private String f_KM_LL9;
    private String f_KM_LL10;
    private String f_KM_LL11;
    private String f_KM_LL12;
    private String f_KM_LL5;
    private String f_KM_LL6;
    private String f_KM_LL7;
    private String f_KM_LL8;
    private String f_KM_LL13;
    private String f_KM_LL14;
    private String f_KM_LL15;
    private String f_KM_LL16;

    private String imgFootTruck;
}
